유저 회원가입 기능 구현 및 테스트케이스 추가
Pilot-Server-Dev/pilot_instagram pull request #3
Opened 2024-11-05 05:49 UTC by kitaee

- 회원가입 API 추가
- 회원가입 테스트케이스 추가
- build.gralde 라이브러리 정리
- JpaAuditingConfig 분리
- AOP 기능 추가 (API 정보, 호출 시간 등)
- API Response 추가 및 ExceptionHandler 정의

---
[로깅 정보 예시 (메소드명, 파라미터, 응답시간, 리턴타입 등)]
![image](https://github.com/user-attachments/assets/fc1d4636-40c3-4d54-996e-b3b998680ac4)

[성공 케이스 API Response]
<img width="522" alt="image" src="https://github.com/user-attachments/assets/f2100ae8-2bbe-4995-9456-f9cf19c296f7">

[실패 케이스 API Response]
<img width="563" alt="image" src="https://github.com/user-attachments/assets/3dfa2326-27ec-45dc-b42d-7e5d3a280da7">

2024-11-08 02:31 UTC, kitaee commented
아이디 중복체크를 까먹고 빠트렸네요 바로 추가해놓겠습니다!

2024-11-08 13:51 UTC, SL313 commented on src/main/java/pilot/instagram/domain/user/UserController.java
> +    @PostMapping("/api/user/new")
UserController이기 때문에 공통 부분은 아래와 같이 빼면 좋을 것 같습니다.
```
@RequestMapping("/api/user")
...
@PostMapping("/new")
```

2024-11-08 13:51 UTC, SL313 commented on src/main/java/pilot/instagram/domain/user/request/UserRequest.java
> +    private String id;
@NotNull을 의도하신거 같은데 exception 메시지 넣으면 좋을 것 같습니다!

2024-11-08 13:51 UTC, SL313 commented on src/main/java/pilot/instagram/domain/user/UserController.java
> +    public ApiResponse<UserResponse> saveUser(@RequestBody UserRequest userRequest) {
UserRequest에서 @NotNull 사용하셔서 @Valid 어노테이션 붙여주셔야 할 것 같습니다!

2024-11-08 13:51 UTC, SL313 commented on src/main/java/pilot/instagram/domain/user/service/UserService.java
> +    }
u -> user 로 명확하게 바꿔주시면 좋을 것 같습니다.

2024-11-08 13:51 UTC, SL313 commented on src/main/java/pilot/instagram/domain/user/service/UserService.java
> +    }
exception 들은 나중에 custom exception 으로 한번에 빼면 좋을 것 같아요!

2024-11-08 13:51 UTC, SL313 commented on src/test/java/pilot/instagram/user/UserServiceTest.java
> +public class UserServiceTest {
test코드에서도 db에서 롤백되도록 확인해주세요!

2024-11-08 13:53 UTC, SL313 reviewed
도메인 구조 변경 부탁드립니다!

최상단 domain -> domain
하위 domain -> entity

2024-11-08 13:54 UTC, SL313 requested changes
단기간에 작업하신건데 정교하게 잘 해주셨네요! 고생 많으셨습니다 :)
리뷰 참고하셔서 몇가지만 수정해주시면 될 것 같습니다.

2024-11-09 04:48 UTC, kitaee commented on src/main/java/pilot/instagram/domain/user/UserController.java
> +    @PostMapping("/api/user/new")
좋은 피드백입니다. 반영해놓겠습니다!

2024-11-09 05:11 UTC, kitaee commented on src/main/java/pilot/instagram/domain/user/request/UserRequest.java
> +    private String id;
@NotNull과 @NonNull의 차이를 모르고 혼용해서 쓰고 있었는데 이 참에 확실하게 알 수 있었습니다!
https://hyeon9mak.github.io/not-null-annotation-exception-handling/

해당 페이지 한번 참고해서 공부해보시면 좋을 것 같아요! 
추가로 NotNull의 메세지를 담아서 null 값이 들어왔을 때 해당 값으로 반환되도록 @Valid 사용해서 ExceptionHandler에서 잡도록 추가했습니다.

2024-11-09 05:12 UTC, kitaee commented on src/main/java/pilot/instagram/domain/user/service/UserService.java
> +    }
반영 완료!

2024-11-09 05:24 UTC, kitaee commented on src/test/java/pilot/instagram/user/UserServiceTest.java
> +public class UserServiceTest {
@Transactional 어노테이션을 사용하면 join 상황에서의 예기치 못한 이슈 때문에 테스트에서 사용하기는 그렇고
@DataJpaTest 같은 경우에는 H2 같은 In-Memory DB를 사용할 때 좋은데

저희 상황은 애매하게 걸쳐있어서 우선 테스트 코드에서 사용한 데이터는 바로바로 지워주도록 tearDown() 메소드를 구현해줬습니다. 추후에 다른 엔티티들까지 테스트를 진행해서 조금 더 넓어졌을 때 In-Memory DB를 도입하면 좋을 것 같아요!

2024-11-09 07:25 UTC, SL313 requested changes
마지막 수정사항 요청이 될 것 같습니다 :) 실수하신 부분 한번만 확인해주세요!

2024-11-09 07:25 UTC, SL313 commented on src/main/java/pilot/instagram/global/ApiControllerAdvice.java
> +        System.out.println(e.getMessage() + "aaaa");
테스트하신 코드 지워주셔야 할 것 같아요.

2024-11-09 07:27 UTC, kitaee commented on src/main/java/pilot/instagram/global/ApiControllerAdvice.java
> +        System.out.println(e.getMessage() + "aaaa");
바보같은 실수였습니다

2024-11-09 07:29 UTC, SL313 approved these changes
고생 많으셨습니다! LGTM ~!

2024-11-09 07:29 UTC, merged