게시글 생성 & 조회 API 구현
Pilot-Server-Dev/pilot_instagram pull request #6
Opened 2024-11-12 05:56 UTC by kitaee

[Exception에 쓰이는 예외 메세지들 Enum에서 전역 관리로 수정]
![image](https://github.com/user-attachments/assets/efbdaefb-5b7a-422b-af62-7b801d031fd7)

[게시글 생성 API 구현]
<img width="475" alt="image" src="https://github.com/user-attachments/assets/c16729d7-7ace-4acc-b1b2-9ec44426f64c">

[게시글 조회 API 구현]
<img width="474" alt="image" src="https://github.com/user-attachments/assets/412b5ff6-c6fc-4949-a2d3-a820ae17d97b">

2024-11-12 11:42 UTC, SL313 requested changes
고생하셨습니다. 짧은 시간 내에 많이 구현하셨네요.

2024-11-12 11:42 UTC, SL313 commented on src/main/java/pilot/instagram/domain/post/entity/Post.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
user entity 에서는 아래와 같이 작성하셨던데 규격 맞춰주시면 좋을 것 같습니다!

<img width="454" alt="image" src="https://github.com/user-attachments/assets/46861226-b7bb-459c-bd98-8d3f1109eb7b">

2024-11-12 11:42 UTC, SL313 commented on src/main/java/pilot/instagram/domain/post/entity/Post.java
> +    }
메소드명이 기능과 상이한 것 같습니다.

2024-11-12 11:42 UTC, SL313 commented on src/main/java/pilot/instagram/domain/post/service/PostService.java
> +    }
이렇게 한줄에 return 하는 것이 좋은 방식인가요? 해당 과정 내에서 터지는 오류는 어떻게 핸들링 되는지 궁금합니다.

2024-11-12 11:42 UTC, SL313 commented on src/main/java/pilot/instagram/exception/ErrorCode.java
> +    POST_NOT_FOUND("게시글을 찾을 수 없습니다.");
오류 문구에 붙는 별도의 코드는 없는걸까요?

2024-11-12 11:45 UTC, kitaee commented on src/main/java/pilot/instagram/domain/post/entity/Post.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
넵 통일시켜놓겠습니다!

2024-11-12 11:53 UTC, kitaee commented on src/main/java/pilot/instagram/exception/ErrorCode.java
> +    POST_NOT_FOUND("게시글을 찾을 수 없습니다.");
클라이언트와 소통하는 에러가 아니고 각 에러명/메세지로 충분히 관리가 가능하다 생각해 별도의 코드는 추가안해줬는데 코드를 추가하는 것이 좋을까요?

2024-11-16 03:09 UTC, SL313 commented on src/main/java/pilot/instagram/exception/ErrorCode.java
> +    POST_NOT_FOUND("게시글을 찾을 수 없습니다.");
개인적인 생각으로는 오류 구분을 위해서 있으면 좋을 것 같기는 한데, 없어도 괜찮을 것 같습니다!

2024-11-16 03:10 UTC, SL313 approved these changes

2024-11-16 03:10 UTC, merged